let code1;
code1 = 7 + 3;
let code2;
code2 = 100 / 2 - 10;
let code3;
code3 = 40 % 1 + 39;
let message;
message = "The vault has been secured. The combination is:";
let codeA;
codeA = code1 + "-" + code2 + "-" + code3;
let codeB = `${code1}-${code2}-${code3}`;
console.log('message');
console.log('codeA');
console.log('codeB');